[registries.crates-io]
protocol = "sparse"

# abort on panic because panicking across languages is unsound.
#[build]
#rustflags = ["-C", "panic=abort"]

# musl targets require -crt-static, panic=abort must be set again because this overrides the
# rustflags set for the build key.
[target.aarch64-unknown-linux-musl]
rustflags = ["-C", "panic=abort", "-C", "target-feature=-crt-static"]

[target.arm-unknown-linux-musleabihf]
rustflags = ["-C", "panic=abort", "-C", "target-feature=-crt-static"]

[target.armv7-unknown-linux-musleabihf]
rustflags = ["-C", "panic=abort", "-C", "target-feature=-crt-static"]

[target.i686-unknown-linux-musl]
rustflags = ["-C", "panic=abort", "-C", "target-feature=-crt-static"]

[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "panic=abort", "-C", "target-feature=-crt-static"]

# For linux-gnu targets, avoid rust-lld issues with compressed debug sections
# by using the GNU linker instead of lld
[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "panic=abort", "-C", "linker=x86_64-linux-gnu-gcc", "-C", "link-arg=-fuse-ld=bfd"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "panic=abort", "-C", "linker=aarch64-linux-gnu-gcc", "-C", "link-arg=-fuse-ld=bfd"]

[target.i686-unknown-linux-gnu]
rustflags = ["-C", "panic=abort", "-C", "linker=i686-linux-gnu-gcc", "-C", "link-arg=-fuse-ld=bfd"]

# On BSD-like platforms, the link-args `-undefined` and `dynamic_lookup` must be set to allow
# calling functions from libjulia without explicitly linking it. Like the musl targets above,
# panic=abort is set again.
[target.aarch64-apple-darwin]
rustflags = ["-C", "panic=abort", "-C", "link-arg=-undefined", "-C", "link-arg=dynamic_lookup"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "panic=abort", "-C", "link-arg=-undefined", "-C", "link-arg=dynamic_lookup"]

[target.x86_64-unknown-freebsd]
rustflags = ["-C", "panic=abort", "-C", "link-arg=-undefined", "-C", "link-arg=dynamic_lookup"]
